### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by emiliacb** [emiliacb/VisualSizer#4]
- [x] deactivate scroll while touch resizing
- [x] deactivate margin auto in the vídeo container

**Comment by emiliacb** [comment]
- [x] reduce the font size of the header in Mobile screens
- [x] deactivate hidden overflow

**Comment by emiliacb** [comment]
- [x] the width at every touch starts in 0

**Comment by Em3c2** [comment]
- [ ] deactivate touch gestures when resizing
